GET http://localhost:8080/car

###


GET http://localhost:8080/car/5

###


GET http://localhost:8080/salon

###

GET http://localhost:8080/salon/2

###

POST http://localhost:8080/salon
Content-Type: application/json

{
  "name": "TEST",
  "address": "TEST"
}


###


POST http://localhost:8080/car
Content-Type: application/json

{
  "brand": "Volvo",
  "model": "V-90.",
  "maxSpeed": 230,
  "salonID": 1
}

###

PUT http://localhost:8080/car/6
Content-Type: application/json

{
  "brand": "Mazda",
  "model": "123",
  "maxSpeed": 220,
  "salonID": 1
}

####

DELETE http://localhost:8080/car/6

####

DELETE http://localhost:8080/salon/3

####


