GET http://localhost:8080/salon

###

GET http://localhost:8080/salon/2

###

POST http://localhost:8080/salon
Content-Type: application/json

{
  "name": "TEST",
  "address": "TEST"
}


###

PUT http://localhost:8080/salon/3
Content-Type: application/json

{
  "name": "TEST",
  "address": "COMPLETE"
}


####

DELETE http://localhost:8080/salon/3

####


